version: '3.8'

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: conveniar_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: conveniar_php
    volumes:
      - ./:/var/www/html

  db:
    image: postgres:14-alpine
    container_name: conveniar_db
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: