CREATE TABLE IF NOT EXISTS fundacoes (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    cnpj VARCHAR(18) NOT NULL UNIQUE,
    email VARCHAR(255),
    telefone VARCHAR(20),
    instituicao_apoiada VARCHAR(255) NOT NULL,
    data_cadastro TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

GRANT ALL PRIVILEGES ON TABLE fundacoes TO ${POSTGRES_USER};
GRANT USAGE, SELECT ON SEQUENCE fundacoes_id_seq TO ${POSTGRES_USER};